#!/usr/bin/env bash
# Configure localhost and facebook.com IP addresses in the hosts file
tmp_file=$(mktemp)

grep -Ev '(^|[[:space:]])(localhost|facebook\.com)([[:space:]]|$)' /etc/hosts > "$tmp_file"

echo "127.0.0.2 localhost" >> "$tmp_file"
echo "8.8.8.8 facebook.com" >> "$tmp_file"

cat "$tmp_file" > /etc/hosts
rm -f "$tmp_file"
