#!/usr/bin/env bash
# Configure localhost and facebook.com IP addresses in the hosts file
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts
sed -i '/[[:space:]]facebook\.com\([[:space:]]\|$\)/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
